name: demo

on:
  # push:
  #   branches: main

  pull_request:
    branches: main
  
  push:
    paths:
    - 'README.md'
  
  issues:
    types: opened

  workflow_dispatch:


jobs:

  Explore-GitHub-Actions:
    runs-on: ubuntu-latest  
    strategy:
      matrix:
        configuration: [debug, release]
    steps:
    - run: echo "🔧 Building the configuration ${{ matrix.configuration }}."

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: run sample jobs
        run: echo Hello World!
        
