name: demo

on:
  push:
    branches: main

  pull_request:
    branches: main
  
  issues:
    types: opened


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: run sample jobs
        run: echo Hello World!
        
